# Generated by Django 4.1.5 on 2023-01-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Polls",
        ),
    ]
